export const LOAD_POST_LIST = 'LOAD_POST_LIST';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';
export const LOAD_POST_FAILURE = 'LOAD_POST_FAIL';
export const LOAD_USER_LIST = 'LOAD_USER_LIST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const GET_COMMENTS = "GET_COMMENTS";

